version: "3.7"

services:
    # image project
    homedev-app:
        container_name: homedev-laravel-9
        build:
            context: .
            dockerfile: Dockerfile
        image: especializati/laravel9-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - laravel-9

    # nginx
    nginx:
        container_name: especializati-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel-9

    # db mysql ${DB_DATABASE} //Busca do arquivo .env
    mysql:
        container_name: especializati-mysql
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3388:3306"
        networks:
            - laravel-9

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        links:
            - mysql
        restart: always
        environment:
            - PMA_ARBITRARY=1
        ports:
            - 8899:80
        networks:
            - laravel-9

networks:
    laravel-9:
        driver: bridge

#Doc. de utilizacao
# para acessar phpmyadmin no navegador: http://localhost:8899/ e a porta
# para acessar nginx(servidor) no navegador: http://localhost:8989/ e a porta

#PHPMYADMIN info no file
# servidor: mysql
# user: root
# pass: root
